require "tecu.plugins"

require "tecu.core.options"
require "tecu.core.keymaps"
require "tecu.core.colorscheme"

require "tecu.plugins.cmp"
require "tecu.plugins.lsp"
require "tecu.plugins.telescope"
require "tecu.plugins.treesitter"
require "tecu.plugins.autopairs"
require "tecu.plugins.comment"
require "tecu.plugins.gitsigns"
require "tecu.plugins.nvim-tree"
require "tecu.plugins.bufferline"
require "tecu.plugins.lualine"
require "tecu.plugins.project"
require "tecu.plugins.indentline"
require "tecu.plugins.impatient"
require "tecu.plugins.alpha"
require "tecu.plugins.autocommands"
require "tecu.plugins.whichkey"
require "tecu.plugins.nvterm"
require "tecu.plugins.prettier"
require "tecu.plugins.autotag"
