# Mountain Theme

[colors]
foreground = "#f0f0f0"
background = "#0f0f0f"
cursor_bg = "#f0f0f0"
cursor_fg = "#f0f0f0"
cursor_border = "#262626"
split = "#4c4c4c"

ansi = [
  "#a291f4",
  "#f49399",
  "#93f496",
  "#f4ed93",
  "#93f2f4",
  "#f493f4",
  "#93f2f4",
  "#e4e4ff",
]
brights = [
  "#a59cde",
  "#fa989e",
  "#98fa9b",
  "#faf298",
  "#98f7fa",
  "#de87de",
  "#98f7fa",
  "#ffe6e6",
]

# ansi_old = [
#   "#8f8aac",
#   "#ac8a8c",
#   "#8aac8b",
#   "#aca98a",
#   "#8aabac",
#   "#ac8aac",
#   "#8aabac",
#   "#e7e7e8",
# ]
# brights_old = [
#   "#a89fe0",
#   "#c49ea0",
#   "#9ec49f",
#   "#c4c19e",
#   "#9ec3c4",
#   "#c49ec4",
#   "#9ec3c4",
#   "#f0f0f0",
# ]
